version: 2.1
commands:
  tests:
    description: Build steps for running the test suite
    steps:
      - run:
          name: Install build packages
          command: apk add --no-cache --no-progress build-base cmake curl-dev git
      - checkout
      - run:
          name: Install Code Climate test reporter
          command: |
            wget -O ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
            chmod +x ./cc-test-reporter
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle exec rubocop
      - run: bundle exec pronto run --commit origin/master --exit-code
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec --format documentation --color spec
            ./cc-test-reporter after-build --exit-code $?
executors:
  ruby:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: docker.io/library/ruby:<< parameters.tag >>
jobs:
  build:
    parameters:
      image-tag:
        type: string
        default: "latest"
    executor:
      name: ruby
      tag: << parameters.image-tag >>
    steps:
      - tests
    working_directory: ~/gem-versioner
workflows:
  multiple-ruby-versions:
    jobs:
      - build:
          image-tag: "2.3-alpine"
      - build:
          image-tag: "2.4-alpine"
      - build:
          image-tag: "2.5-alpine"
