version: 2
jobs:
  build:
    docker:
      - image: docker.io/library/ruby:2.4-alpine
    steps:
      - run:
          name: Install build packages
          command: apk add --no-cache --no-progress build-base cmake git
      - checkout
      - run:
          name: Install Code Climate test reporter
          command: |
            wget -O ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
            chmod +x ./cc-test-reporter
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle exec rubocop
      - run: bundle exec pronto run --commit origin/master --exit-code
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec --format documentation --color spec
            ./cc-test-reporter after-build --exit-code $?
    working_directory: ~/gem-versioner
